import { assetUrl } from "@/lib/supabase-storage";

export const PERSONAL_INFO = {
  name: "Rifqi",
  role: "Information Systems Student",
  location: "Kota Bekasi, Jawa Barat, Indonesia",
  email: "rfqiii1511@gmail.com",

  github: "https://github.com/ki1bot",
  linkedin:
    "https://www.linkedin.com/in/rifq1?utm_source=share_via&utm_content=profile&utm_medium=member_android",
  instagram: "https://www.instagram.com/ki1bot_?igsh=M3o2OTdvb2Q1eXI1",
  spotify:
    "https://open.spotify.com/user/314fig6hgrc2gaq7phryrrmfcp34?si=45c2f5e0cf9e4291",
  youtube: "https://www.youtube.com/@kibot7659",
  tiktok: "https://www.tiktok.com/@kiibott_?_r=1&_t=ZS-96Aalc9CrbQ",

  profileImage: assetUrl("assets/Rifqii.png"),
  description:
    "Saya membangun website modern, responsif, dan terstruktur menggunakan React, Next.js, Tailwind CSS, Shadcn, dan Supabase.",
};

export const TECH_STACK = [
  { name: "HTML", icon: "/img/techstack/html.svg" },
  { name: "CSS", icon: "/img/techstack/css.svg" },
  { name: "JavaScript", icon: "/img/techstack/javascript.svg" },
  { name: "TypeScript", icon: "/img/techstack/typescript.png" },
  { name: "Tailwind CSS", icon: "/img/techstack/tailwind.svg" },
  { name: "Bootstrap", icon: "/img/techstack/bootstrap.svg" },
  { name: "Node.JS", icon: "/img/techstack/nodejs.svg" },
  { name: "Vite", icon: "/img/techstack/vite.svg" },
  { name: "React", icon: "/img/techstack/reactjs.svg" },
  { name: "Angular", icon: "/img/techstack/angular.png" },
  { name: "Vue", icon: "/img/techstack/vue.png" },
  { name: "Nuxt", icon: "/img/techstack/nuxtjs.png" },
  { name: "svelte", icon: "/img/techstack/svelte.png" },
  { name: "Next.JS", icon: "/img/techstack/nextjs.png" },
  { name: "Nest.JS", icon: "/img/techstack/nestjs.png" },
  { name: "Express.JS", icon: "/img/techstack/expressjs.png" },
  { name: "Inertia.JS", icon: "/img/techstack/inertiajs.png" },
  { name: "PHP", icon: "/img/techstack/php.png" },
  { name: "Code Igniter", icon: "/img/techstack/codeigniter.png" },
  { name: "Laravel", icon: "/img/techstack/laravel.png" },
  { name: "Java", icon: "/img/techstack/java.png" },
  { name: "Dart", icon: "/img/techstack/dart.png" },
  { name: "Flutter", icon: "/img/techstack/flutter.png" },
  { name: "Golang", icon: "/img/techstack/golang.png" },
  { name: "Python", icon: "/img/techstack/python.png" },
  { name: "C", icon: "/img/techstack/c.png" },
  { name: "C++", icon: "/img/techstack/c++.png" },
  { name: "Firebase", icon: "/img/techstack/firebase.svg" },
  { name: "Supabase", icon: "/img/techstack/supabase.png" },
  { name: "MySQL", icon: "/img/techstack/mysql.png" },
  { name: "PostgreSQL", icon: "/img/techstack/postgresql.png" },
  { name: "MongoDB", icon: "/img/techstack/mongodb.png" },
  { name: "Prisma", icon: "/img/techstack/prismaorm.png" },
  { name: "Docker", icon: "/img/techstack/docker.png" },
  { name: "Vercel", icon: "/img/techstack/vercel.svg" },
  { name: "Linux", icon: "/img/techstack/linux.png" },
];

export const FALLBACK_PROJECTS = [
  {
    id: 1,
    title: "Sistem Marketplace Broker",
    description:
      "Dashboard sistem marketplace broker yang dibangun menggunakan Laravel 12 sebagai backend, ReactJS sebagai frontend, dan MySQL sebagai database. Sistem ini digunakan untuk mengelola broker, seller, buyer, produk, transaksi, negosiasi, komisi, dan riwayat transaksi dalam satu tampilan modern.",
    img: assetUrl("projects/MarketPlaceBroker.png"),
    link: "https://sistemmarketplacebroker.page.gd/",
    github: "https://github.com/ki1bot/sistem-marketplace-broker.git",
    features: [
      "Frontend menggunakan ReactJS, Backend menggunakan Laravel 12 dan Database menggunakan MySQL",
      "Dashboard utama dan Manajemen broker",
      "Manajemen seller, buyer dan Data produk marketplace",
      "Transaksi, Negosiasi dan Riwayat transaksi",
      "Komisi broker, Visualisasi grafik produk dan status transaksi",
    ],
    tech_stack: [
      "Laravel 12",
      "ReactJS",
      "MySQL",
      "JavaScript",
      "Tailwind CSS",
    ],
    is_published: true,
    order_index: 1,
  },
  {
    id: 2,
    title: "Azzahra Perwira",
    description:
      "Website profil dan sistem pengelolaan konten untuk Yayasan Azzahra Perwira. Website ini menampilkan informasi yayasan, profil lembaga, tenaga pengajar, unit KB/TK, TPQ, daycare, program lansia, berita, kegiatan, brosur, dan informasi kontak. Administrator dapat mengelola teks, gambar, dokumen PDF, urutan tampilan, serta status konten melalui dashboard admin tanpa harus mengubah kode website secara langsung.",
    img: assetUrl("projects/adminUiYayasan.png"),
    link: "https://azzahra-perwira.xo.je/",
    github: "https://github.com/ki1bot/azzahraperwira.git",
    features: [
      "Halaman publik yang mencakup Beranda, Profil Yayasan, Tenaga Pengajar, Unit KB/TK, Unit TPQ, Unit Daycare, Unit Lansia, serta Informasi dan Berita",
      "Dashboard administrator untuk mengelola seluruh konten website dari satu panel",
      "Sistem login admin berbasis session dengan pembatasan akses menggunakan filter autentikasi",
      "Pengelolaan teks, judul, gambar, dokumen, urutan tampilan, dan status aktif atau nonaktif pada setiap konten",
      "Manajemen data tenaga pengajar beserta foto, kategori, pendidikan, urutan, dan status publikasi",
      "Pengelolaan berita dan informasi dinamis yang memiliki halaman detail berdasarkan kode konten",
      "Upload gambar JPG, JPEG, PNG, dan WebP dengan ukuran maksimal 2 MB",
      "Upload dokumen brosur dalam format PDF dengan ukuran maksimal 10 MB",
      "Penghapusan otomatis terhadap file gambar atau dokumen lama ketika media diperbarui atau konten dihapus",
      "Perlindungan struktur utama halaman dengan membatasi konten tetap agar tidak dapat dihapus sembarangan",
      "Pengelolaan footer yang mencakup identitas yayasan, alamat, WhatsApp, Instagram, TikTok, dan informasi hak cipta",
      "Fitur ubah password dan logout administrator",
      "Tampilan responsif untuk halaman publik dan dashboard admin serta dukungan tema terang dan gelap pada panel administrator",
    ],
    tech_stack: [
      "PHP",
      "CodeIgniter 4",
      "MySQL",
      "Tailwind CSS",
      "Alpine.js",
      "JavaScript",
      "Composer",
    ],
    is_published: true,
    order_index: 2,
  },
  {
    id: 3,
    title: "QR Code Generator",
    description:
      "Aplikasi web generate QR Code yang dibuat menggunakan React, TypeScript, Vite, Tailwind CSS, dan qrcode.react. Project ini mendukung pembuatan QR Code untuk URL, domain, Gmail, WhatsApp, telepon, SMS, dan teks biasa. Aplikasi juga dilengkapi fitur tema terang dan gelap, custom warna QR Code, preview real-time, copy target output, serta download QR Code dalam format PNG.",
    img: assetUrl("projects/ProjectQrcode.png"),
    link: "https://generate-qrcode-one.vercel.app/",
    github: "https://github.com/ki1bot/generate-qrcode.git",
    features: [
      "Generate QR Code secara real-time dari input user",
      "Mendukung URL, domain, Gmail, WhatsApp, telepon, SMS, dan teks biasa",
      "Teks biasa otomatis diarahkan ke halaman browser yang menampilkan teks tersebut",
      "Custom warna QR Code dan warna background QR Code",
      "Fitur download QR Code sebagai PNG dan copy target output",
      "Tema terang dan tema gelap dengan tombol icon sun dan moon",
      "Responsive untuk desktop dan mobile",
    ],
    tech_stack: [
      "Vite",
      "React",
      "JavaScript",
      "TypeScript",
      "Tailwind CSS",
      "qrcode.react",
    ],
    is_published: true,
    order_index: 3,
  },
  {
    id: 4,
    title: "Generate Tugas",
    description: "Coming Soon",
    img: assetUrl("projects/ComingSoon.png"),
    link: "https://generate-tugas.vercel.app/",
    github: "https://github.com/ki1bot/generate-tugas.git",
    features: ["", "", "", "", "", "", ""],
    tech_stack: ["", "", "", "", "", ""],
    is_published: true,
    order_index: 4,
  },
  {
    id: 5,
    title: "Pelayanan Jasa AC",
    description:
      "Website layanan jasa AC berbasis Laravel untuk mengelola layanan, pemesanan, detail pesanan, pembayaran, autentikasi pelanggan, serta panel admin untuk memproses status pesanan.",
    img: assetUrl("projects/PelayananJasaAc.png"),
    link: "https://pelayananjasaac.rf.gd/",
    github: "https://github.com/ki1bot/pelayananjasaac.git",
    pdf: assetUrl("projects/TugasAlgo2APelayananJasaAc.pdf"),
    features: [
      "Halaman beranda dan daftar layanan jasa AC",
      "Registrasi dan login pelanggan",
      "Pembuatan pesanan layanan oleh pelanggan",
      "Pengelolaan detail pesanan seperti layanan, merk AC, lokasi, dan tarif jarak",
      "Fitur pembayaran untuk pesanan pelanggan",
      "Panel admin untuk melihat dan memproses pesanan",
      "Manajemen status pesanan dari proses sampai selesai",
    ],
    tech_stack: ["Laravel", "PHP", "Blade", "Tailwind CSS", "Vite", "MySQL"],
    is_published: true,
    order_index: 5,
  },
  {
    id: 6,
    title: "Generate Website To PDF",
    description:
      "Website yang membantu pengguna mengubah halaman website menjadi file PDF dengan mudah. Pengguna cukup memasukkan alamat website, menentukan judul, nama file, dan jumlah halaman yang ingin dibuat.",
    img: assetUrl("projects/GeneratePDF.png"),
    link: "https://pdf-generate-nu.vercel.app/",
    github: "https://github.com/ki1bot/pdf-generate.git",
    features: [
      "Mengubah halaman website menjadi file PDF",
      "Menentukan judul yang tampil pada PDF",
      "Mengatur nama file PDF sesuai kebutuhan",
      "Membatasi jumlah halaman yang ingin dibuat",
      "Menampilkan alamat website dan nomor halaman pada PDF",
      "Mengunduh file PDF secara otomatis setelah selesai dibuat",
    ],
    tech_stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Express.js",
      "Playwright",
      "pdf-lib",
    ],
    is_published: true,
    order_index: 6,
  },
  {
    id: 7,
    title: "Realtime Collaborative Notes",
    description:
      "Aplikasi web untuk membuat, mengelola, dan membagikan catatan kepada pengguna lain. Aplikasi menyediakan autentikasi email dan Google, pengelolaan catatan, pencarian, pembagian akses berdasarkan role owner, editor, dan viewer, serta riwayat aktivitas. Perubahan catatan disimpan secara manual melalui Next.js Route Handler dan data disimpan menggunakan MongoDB.",
    img: assetUrl("projects/realtimecollaborativenotes.png"),
    link: "https://realtimecollaborativenotes.vercel.app/",
    github: "https://github.com/ki1bot/realtimecollaborativenotes.git",
    features: [
      "Halaman utama dapat diakses oleh pengunjung tanpa harus login",
      "Registrasi dan login menggunakan email serta password",
      "Login menggunakan akun Google melalui Google OAuth",
      "Autentikasi API menggunakan JSON Web Token dengan session pengguna yang disimpan di sessionStorage",
      "Membuat, membaca, mengedit, menyimpan, dan menghapus catatan",
      "Pencarian catatan berdasarkan judul, isi, atau nama pemilik",
      "Pembagian catatan kepada pengguna lain sebagai viewer atau editor",
      "Proteksi akses berdasarkan role owner, editor, dan viewer pada frontend serta backend",
      "Pencarian pengguna berdasarkan nama atau email sebelum menambahkan collaborator",
      "Pengelolaan collaborator berupa penambahan, perubahan role, dan penghapusan akses",
      "Riwayat aktivitas untuk pembuatan, perubahan, pembagian, dan penghapusan catatan",
      "Pembaruan activity log secara berkala setiap delapan detik",
      "Informasi jumlah kata, waktu perubahan terakhir, dan pengguna terakhir yang mengedit catatan",
      "Fitur ubah password dan logout pengguna",
      "Tampilan responsif untuk desktop dan perangkat seluler dengan dukungan light mode dan dark mode",
    ],
    tech_stack: [
      "TypeScript",
      "Next.js",
      "React",
      "TypeScript",
      "MongoDB",
      "Mongoose",
      "Tailwind CSS",
      "Axios",
      "JSON Web Token",
      "bcryptjs",
      "Google OAuth",
      "Google Auth Library",
      "React OAuth Google",
      "Lucide React",
    ],
    is_published: true,
    order_index: 7,
  },
  {
    id: 8,
    title: "The Flea Defender",
    description:
      "Game Ini adalah Tugas akhir kelompok 1, yang berbasis game RPG survival desktop berbasis Java Swing, pemain bertahan dari serangan Flea dengan sistem HP, RP, animasi, dan sound effect.",
    img: assetUrl("projects/flea-defender.png"),
    link: "/games/The%20Flea%20Defender-1.0.0.exe",
    github: "https://github.com/ki1bot/The-Flea-Defender.git",
    features: [
      "Game RPG survival berbasis GUI desktop",
      "Sistem HP dan Resource Points untuk Defender",
      "Flea muncul berkala dan menyerang otomatis",
      "Aksi serang, latihan, beli vitamin, dan bertahan",
      "Animasi karakter Defender dan Flea menggunakan sprite sheet",
      "Sound effect dan tombol suara ON/OFF",
      "Progress bar status HP, RP, waktu, dan guard",
      "Sistem menang jika bertahan sampai 300 detik",
    ],
    tech_stack: [
      "Java",
      "Java Swing",
      "Java AWT",
      "Java Sound API",
      "OOP",
      "Sprite Sheet Animation",
    ],
    is_published: true,
    order_index: 8,
  },
  {
    id: 9,
    title: "Kalkulator Ilmiah",
    description:
      "Kalkulator berbasis website yang dapat digunakan untuk menyelesaikan perhitungan dasar maupun perhitungan ilmiah. Pengguna dapat menghitung berbagai rumus matematika, menyimpan hasil perhitungan, dan melihat kembali riwayat perhitungan sebelumnya.",
    img: assetUrl("projects/KalkulatorIlmiah.png"),
    link: "https://kalkulator-ilmiah-two.vercel.app/",
    github: "https://github.com/ki1bot/kalkulator-ilmiah.git",
    features: [
      "Melakukan perhitungan dasar seperti penjumlahan, pengurangan, perkalian, dan pembagian",
      "Menghitung fungsi ilmiah seperti trigonometri, logaritma, akar, pangkat, faktorial, dan persen",
      "Mengubah mode perhitungan sudut antara derajat dan radian",
      "Menyimpan dan menggunakan kembali angka melalui fitur memori kalkulator",
      "Menampilkan hasil sementara sebelum perhitungan diselesaikan",
      "Menyimpan riwayat perhitungan agar dapat digunakan kembali",
      "Mendukung penggunaan tombol keyboard untuk melakukan perhitungan",
      "Menyalin hasil perhitungan ke clipboard dengan mudah",
    ],
    tech_stack: [
      "Vue 3",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Local Storage",
      "Web Clipboard API",
    ],
    is_published: true,
    order_index: 9,
  },
  {
    id: 10,
    title: "Debugging Pemrograman",
    description:
      "Platform pembelajaran debugging pemrograman berbasis web yang menyediakan 64 tantangan dalam bahasa C, C++, Go, Java, JavaScript, PHP, Python, dan SQL. Pengguna dapat menemukan lokasi bug, memperbaiki kode melalui CodeMirror, menjalankan kode menggunakan Judge0, menjelaskan penyebab kesalahan, menggunakan hint, memperoleh skor dan poin, memantau progres, melihat riwayat pengerjaan, serta bersaing melalui leaderboard. Aplikasi juga menyediakan dashboard administrator untuk mengelola tantangan, kategori, tingkat kesulitan, solusi, hint, pengguna, submission, dan statistik aplikasi.",
    img: assetUrl("projects/DebuggingPemrograman.png"),
    link: "https://debugging-pemrograman.vercel.app/",
    github: "https://github.com/ki1bot/debugging-pemrograman.git",
    features: [
      "Registrasi, login, logout, reset password, pengelolaan profil, dan pembagian akses berdasarkan role pengguna dan administrator",
      "Menyediakan 64 tantangan debugging untuk C, C++, Go, Java, JavaScript, PHP, Python, dan SQL",
      "Setiap bahasa memiliki delapan tantangan dengan tingkat kesulitan mudah, menengah, dan sulit",
      "Pencarian dan filter tantangan berdasarkan judul, bahasa pemrograman, serta tingkat kesulitan",
      "Penyelesaian tantangan melalui tiga tahap utama: menentukan baris yang salah, memperbaiki kode, dan menjelaskan penyebab bug",
      "Code editor berbasis CodeMirror dengan syntax highlighting yang menyesuaikan bahasa pemrograman pada setiap tantangan",
      "Eksekusi kode melalui Judge0 dengan dukungan standard input, standard output, compile output, status eksekusi, waktu, dan penggunaan memori",
      "Sistem penilaian berdasarkan ketepatan lokasi bug, kesesuaian kode perbaikan, dan kata kunci pada penjelasan pengguna",
      "Hint bertahap dengan penalti skor serta pembahasan, solusi utama, dan alternatif solusi setelah tantangan berhasil diselesaikan",
      "Penyimpanan riwayat pengerjaan, jumlah percobaan, skor terbaik, total poin, progres tantangan, dan leaderboard pengguna",
      "Dashboard administrator untuk mengelola kategori, tingkat kesulitan, tantangan, hint, solusi, pengguna, submission, dan statistik aplikasi",
    ],
    tech_stack: [
      "PHP",
      "Laravel 13",
      "Laravel Breeze",
      "ReactJS",
      "TypeScript",
      "Inertia.js",
      "PostgreSQL",
      "Tailwind CSS",
      "Vite",
      "CodeMirror",
      "Recharts",
      "Judge0",
    ],
    is_published: true,
    order_index: 10,
  },
  {
    id: 11,
    title: "Aksesibilitas Website",
    description:
      "AksesCheck ID adalah aplikasi pemeriksaan aksesibilitas website yang memindai satu halaman berdasarkan aturan WCAG 2.2 Level A dan AA yang dapat diperiksa secara otomatis oleh axe-core. Proses scan dijalankan melalui antrean Redis dan Asynq menggunakan worker Go, Chromium, dan chromedp. Hasil pemeriksaan menampilkan skor indikator internal, tingkat dampak pelanggaran, aturan yang dilanggar, DOM snippet, selector, failure summary, saran perbaikan, pemeriksaan manual, histori scan, serta laporan JSON dan PDF. Aplikasi juga dilengkapi autentikasi berbasis session cookie HTTP-only, perlindungan CSRF, validasi SSRF, rate limiting, dan pembatasan resource.",
    img: assetUrl("projects/AksesibilitasWebsite.png"),
    link: "https://aksesibilitas-website.vercel.app/",
    github: "https://github.com/ki1bot/aksesibilitas-website.git",
    features: [
      "Registrasi, login, logout, dan autentikasi menggunakan session cookie HTTP-only",
      "Perlindungan request menggunakan CSRF dan pembatasan request melalui rate limiting",
      "Pembuatan dan pengelolaan project website yang akan diperiksa",
      "Pemindaian otomatis terhadap satu halaman website pada setiap scan",
      "Antrean proses scan menggunakan Redis dan Asynq dengan API dan worker yang berjalan sebagai proses terpisah",
      "Status scan queued, running, completed, failed, dan cancelled",
      "Pembatalan serta pengulangan scan yang gagal atau perlu dijalankan kembali",
      "Pemeriksaan aturan WCAG 2.2 Level A dan AA yang didukung oleh axe-core",
      "Pengelompokan pelanggaran berdasarkan tingkat dampak critical, serious, moderate, dan minor",
      "Perhitungan skor otomatis sebagai indikator internal berdasarkan jumlah dan tingkat dampak pelanggaran",
      "Detail pelanggaran berupa aturan, DOM snippet, selector, failure summary, dan referensi perbaikan",
      "Checklist pemeriksaan manual untuk masalah aksesibilitas yang tidak dapat dipastikan melalui pemeriksaan otomatis",
      "Histori scan untuk melihat hasil pemeriksaan website sebelumnya",
      "Pembuatan dan pengunduhan laporan hasil pemeriksaan dalam format JSON dan PDF",
      "Validasi SSRF untuk menolak localhost, alamat private, link-local, multicast, cloud metadata, serta URL berisiko lainnya",
      "Pembatasan request halaman, ukuran data, redirect, navigasi, durasi scan, dan proses download",
      "OpenAPI sebagai kontrak antara backend Go dan frontend TypeScript",
    ],
    tech_stack: [
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Next.JS",
      "TanStack Query",
      "React Hook Form",
      "Zod",
      "Recharts",
      "Lucide React",
      "Sonner",
      "Go",
      "chi",
      "pgx",
      "sqlc",
      "Goose",
      "PostgreSQL",
      "Redis",
      "Asynq",
      "Chromium",
      "chromedp",
      "axe-core",
      "OpenAPI",
      "openapi-fetch",
      "openapi-typescript",
    ],
    is_published: true,
    order_index: 11,
  },
  {
    id: 12,
    title: "Asisten Akademik",
    description:
      "KampusHub adalah platform produktivitas akademik berbasis web dan mobile yang membantu mahasiswa mengelola semester, mata kuliah, jadwal kuliah, tugas, ujian, presensi, nilai, IP semester, serta notifikasi dalam satu sistem. Aplikasi menyediakan dashboard akademik untuk menampilkan semester aktif, jadwal hari ini, tugas mendatang dan terlambat, ujian terdekat, ringkasan presensi, nilai semester, notifikasi, serta persentase penyelesaian tugas. Backend dibangun menggunakan NestJS dan Prisma dengan PostgreSQL, sedangkan aplikasi web menggunakan Next.js dan aplikasi mobile menggunakan Expo serta React Native.",
    img: assetUrl("projects/AsistenAkademik.png"),
    link: "",
    github: "https://github.com/ki1bot/asisten-akademik.git",
    features: [
      "Registrasi, login, refresh token, logout, dan logout dari seluruh perangkat",
      "Verifikasi email, lupa password, dan reset password pengguna",
      "Manajemen session pengguna beserta informasi perangkat, alamat IP, user agent, waktu kedaluwarsa, dan pencabutan session",
      "Pengelolaan profil akademik yang mencakup nama, NPM, universitas, fakultas, jurusan, dan zona waktu",
      "Pengelolaan semester ganjil dan genap berdasarkan tahun akademik, tanggal mulai, tanggal selesai, dan status semester aktif",
      "Pengelolaan mata kuliah beserta kode, jumlah SKS, dosen, ruang, warna, dan catatan",
      "Pengelolaan jadwal kuliah berdasarkan hari, jam mulai, jam selesai, ruang, jenis perkuliahan offline, online, atau hybrid, serta tautan kelas online",
      "Pengelolaan tugas berdasarkan mata kuliah, deadline, deskripsi, lampiran, waktu pengingat, prioritas, dan status pengerjaan",
      "Status tugas TODO, IN_PROGRESS, SUBMITTED, COMPLETED, dan OVERDUE dengan pembaruan otomatis untuk tugas yang terlambat",
      "Pengelolaan jadwal ujian berupa UTS, UAS, kuis, praktikum, presentasi, dan sidang",
      "Pencatatan presensi dengan status hadir, izin, sakit, tidak hadir, dibatalkan, dan kelas pengganti",
      "Pengelolaan nilai akhir dan komponen nilai berdasarkan nama komponen, skor, serta bobot penilaian",
      "Perhitungan nilai akhir berbobot, nilai huruf, bobot mutu, jumlah SKS, jumlah mutu, dan IP semester",
      "Pengelolaan notifikasi sistem, tugas, jadwal, ujian, presensi, dan nilai dengan status sudah atau belum dibaca",
      "Dashboard ringkasan semester aktif, jadwal hari ini, tugas mendatang, tugas terlambat, ujian terdekat, presensi, nilai, dan notifikasi",
      "Statistik produktivitas berdasarkan jumlah tugas, tugas selesai, dan persentase penyelesaian",
      "Aplikasi web responsif menggunakan Next.js dan aplikasi mobile menggunakan Expo serta React Native",
      "Monorepo dengan kontrak tipe, validasi, dan konfigurasi API client yang digunakan bersama oleh web, mobile, dan backend",
    ],
    tech_stack: [
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Next.JS",
      "Nest.JS",
      "Prisma",
      "PostgreSQL",
      "Passport",
      "Argon2",
      "Swagger",
      "TanStack Query",
      "React Hook Form",
      "Zod",
      "Axios",
      "Zustand",
      "Recharts",
      "Lucide React",
      "Sonner",
      "Expo 54",
      "React Native",
      "Expo Router",
      "Expo Secure Store",
      "pnpm Workspace",
      "Turborepo",
      "Jest",
    ],
    is_published: true,
    order_index: 12,
  },
];

export const FALLBACK_CERTIFICATES = [
  {
    id: 1,
    title: "Dicoding Certificate 1",
    img: assetUrl("sertifikat/dicoding1.png"),
    pdf_url: assetUrl("sertifikat/dicoding1.pdf"),
    type: "pdf",
    order_index: 1,
  },
  {
    id: 2,
    title: "Dicoding Certificate 2",
    img: assetUrl("sertifikat/dicoding2.png"),
    pdf_url: assetUrl("sertifikat/dicoding2.pdf"),
    type: "pdf",
    order_index: 2,
  },
  {
    id: 3,
    title: "Dicoding Certificate 3",
    img: assetUrl("sertifikat/dicoding3.png"),
    pdf_url: assetUrl("sertifikat/dicoding3.pdf"),
    type: "pdf",
    order_index: 3,
  },
  {
    id: 4,
    title: "Dicoding Certificate 4",
    img: assetUrl("sertifikat/dicoding4.png"),
    pdf_url: assetUrl("sertifikat/dicoding4.pdf"),
    type: "pdf",
    order_index: 4,
  },
  {
    id: 5,
    title: "Dicoding Certificate 5",
    img: assetUrl("sertifikat/dicoding5.png"),
    pdf_url: assetUrl("sertifikat/dicoding5.pdf"),
    type: "pdf",
    order_index: 5,
  },
  {
    id: 6,
    title: "Dicoding Certificate 6",
    img: assetUrl("sertifikat/dicoding6.png"),
    pdf_url: assetUrl("sertifikat/dicoding6.pdf"),
    type: "pdf",
    order_index: 6,
  },
  {
    id: 7,
    title: "Dicoding Certificate 7",
    img: assetUrl("sertifikat/dicoding7.png"),
    pdf_url: assetUrl("sertifikat/dicoding7.pdf"),
    type: "pdf",
    order_index: 7,
  },
  {
    id: 8,
    title: "Dicoding Certificate 8",
    img: assetUrl("sertifikat/dicoding8.png"),
    pdf_url: assetUrl("sertifikat/dicoding8.pdf"),
    type: "pdf",
    order_index: 8,
  },
  {
    id: 9,
    title: "Dicoding Certificate 9",
    img: assetUrl("sertifikat/dicoding9.png"),
    pdf_url: assetUrl("sertifikat/dicoding9.pdf"),
    type: "pdf",
    order_index: 9,
  },
  {
    id: 10,
    title: "RevoU Certificate Data Analytics",
    img: assetUrl("sertifikat/RevoU-DataAnalytics.png"),
    pdf_url: assetUrl("sertifikat/RevoU-DataAnalytics.pdf"),
    type: "pdf",
    order_index: 10,
  },
  {
    id: 11,
    title: "RevoU Certificate Software Engineering",
    img: assetUrl("sertifikat/RevoU-SoftwareEngineering.png"),
    pdf_url: assetUrl("sertifikat/RevoU-SoftwareEngineering.pdf"),
    type: "pdf",
    order_index: 11,
  },
  {
    id: 12,
    title: "Sertifikat LSP Semester 1",
    img: assetUrl("sertifikat/sertifikatlsp-semester1.png"),
    pdf_url: assetUrl("sertifikat/sertifikatlsp-semester1.pdf"),
    type: "pdf",
    order_index: 12,
  },
  {
    id: 13,
    title: "Sertifikat LSP Semester 2",
    img: assetUrl("sertifikat/sertifikatlsp-semester2.png"),
    pdf_url: assetUrl("sertifikat/sertifikatlsp-semester2.pdf"),
    type: "pdf",
    order_index: 13,
  },
  {
    id: 14,
    title: "Sertifikat Kompetensi",
    img: assetUrl("sertifikat/SertifikatKompetensi.png"),
    pdf_url: assetUrl("sertifikat/SertifikatKompetensi.pdf"),
    type: "pdf",
    order_index: 14,
  },
];

export const FALLBACK_COMMENTS = [
  {
    id: "fallback-pinned-comment",
    user_name: "Rifqi",
    content: "Halo, terima kasih sudah mampir ke portofolio saya.",
    profile_image: assetUrl("assets/rifqi.jpg"),
    is_pinned: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "fallback-guest-comment",
    user_name: "Faris",
    content: "Portofolionya rapi dan bagus banget.",
    profile_image: assetUrl("screen/default-avatar.jpg"),
    is_pinned: false,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];
